/*
 * generated by Xtext
 */
package fr.istic.idm.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractCssDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(fr.istic.idm.cssDsl.CssDslPackage.eINSTANCE);
		return result;
	}
}
