/*
* generated by Xtext
*/
package fr.istic.idm;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PivotMMDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.istic.idm.ui.internal.PivotMMDslActivator.getInstance().getInjector("fr.istic.idm.PivotMMDsl");
	}
	
}
