/**
 * generated by Xtext
 */
package fr.istic.idm.validation;

import fr.istic.idm.validation.AbstractQuestionnaireDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class QuestionnaireDslValidator extends AbstractQuestionnaireDslValidator {
}
