/**
 * generated by Xtext
 */
package fr.istic.idm.serializer;

import fr.istic.idm.serializer.AbstractPivotMMDslSemanticSequencer;

@SuppressWarnings("all")
public class PivotMMDslSemanticSequencer extends AbstractPivotMMDslSemanticSequencer {
}
