/**
 * generated by Xtext
 */
package fr.istic.idm.serializer;

import fr.istic.idm.serializer.AbstractPivotMMDslSyntacticSequencer;

@SuppressWarnings("all")
public class PivotMMDslSyntacticSequencer extends AbstractPivotMMDslSyntacticSequencer {
}
