/*
 * generated by Xtext
 */
package fr.istic.idm.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.istic.idm.ui.internal.PivotMMDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PivotMMDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PivotMMDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PivotMMDslActivator.getInstance().getInjector(PivotMMDslActivator.FR_ISTIC_IDM_PIVOTMMDSL);
	}
	
}
