/*
* generated by Xtext
*/
package fr.istic.idm.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class PivotMMDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class PollSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PollSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPollSystemAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPollSystemKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTitleKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTitleAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_3_1_0 = (RuleCall)cTitleAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cModelsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cModelsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cModelsUiModelParserRuleCall_4_2_0 = (RuleCall)cModelsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cModelsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cModelsUiModelParserRuleCall_4_3_1_0 = (RuleCall)cModelsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//PollSystem:
		//	{PollSystem} "PollSystem" "{" ("title" title=EString)? ("models" "{" models+=UiModel ("," models+=UiModel)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{PollSystem} "PollSystem" "{" ("title" title=EString)? ("models" "{" models+=UiModel ("," models+=UiModel)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{PollSystem}
		public Action getPollSystemAction_0() { return cPollSystemAction_0; }

		//"PollSystem"
		public Keyword getPollSystemKeyword_1() { return cPollSystemKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("title" title=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"title"
		public Keyword getTitleKeyword_3_0() { return cTitleKeyword_3_0; }

		//title=EString
		public Assignment getTitleAssignment_3_1() { return cTitleAssignment_3_1; }

		//EString
		public RuleCall getTitleEStringParserRuleCall_3_1_0() { return cTitleEStringParserRuleCall_3_1_0; }

		//("models" "{" models+=UiModel ("," models+=UiModel)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"models"
		public Keyword getModelsKeyword_4_0() { return cModelsKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//models+=UiModel
		public Assignment getModelsAssignment_4_2() { return cModelsAssignment_4_2; }

		//UiModel
		public RuleCall getModelsUiModelParserRuleCall_4_2_0() { return cModelsUiModelParserRuleCall_4_2_0; }

		//("," models+=UiModel)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//models+=UiModel
		public Assignment getModelsAssignment_4_3_1() { return cModelsAssignment_4_3_1; }

		//UiModel
		public RuleCall getModelsUiModelParserRuleCall_4_3_1_0() { return cModelsUiModelParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class WidgetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Widget");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCheckBoxParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRadioButtonParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTextFieldParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cComboBoxParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Widget:
		//	CheckBox | RadioButton | TextField | ComboBox;
		public ParserRule getRule() { return rule; }

		//CheckBox | RadioButton | TextField | ComboBox
		public Alternatives getAlternatives() { return cAlternatives; }

		//CheckBox
		public RuleCall getCheckBoxParserRuleCall_0() { return cCheckBoxParserRuleCall_0; }

		//RadioButton
		public RuleCall getRadioButtonParserRuleCall_1() { return cRadioButtonParserRuleCall_1; }

		//TextField
		public RuleCall getTextFieldParserRuleCall_2() { return cTextFieldParserRuleCall_2; }

		//ComboBox
		public RuleCall getComboBoxParserRuleCall_3() { return cComboBoxParserRuleCall_3; }
	}

	public class UiModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UiModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUiModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUiModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIdKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cIdAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_3_1_0 = (RuleCall)cIdAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLaQuestionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLaQuestionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLaQuestionEStringParserRuleCall_4_1_0 = (RuleCall)cLaQuestionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cWidgetsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cWidgetsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cWidgetsWidgetParserRuleCall_5_2_0 = (RuleCall)cWidgetsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cWidgetsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cWidgetsWidgetParserRuleCall_5_3_1_0 = (RuleCall)cWidgetsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//UiModel:
		//	{UiModel} "UiModel" "{" ("id" id=EString)? ("laQuestion" laQuestion=EString)? ("widgets" "{" widgets+=Widget (","
		//	widgets+=Widget)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{UiModel} "UiModel" "{" ("id" id=EString)? ("laQuestion" laQuestion=EString)? ("widgets" "{" widgets+=Widget (","
		//widgets+=Widget)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{UiModel}
		public Action getUiModelAction_0() { return cUiModelAction_0; }

		//"UiModel"
		public Keyword getUiModelKeyword_1() { return cUiModelKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("id" id=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"id"
		public Keyword getIdKeyword_3_0() { return cIdKeyword_3_0; }

		//id=EString
		public Assignment getIdAssignment_3_1() { return cIdAssignment_3_1; }

		//EString
		public RuleCall getIdEStringParserRuleCall_3_1_0() { return cIdEStringParserRuleCall_3_1_0; }

		//("laQuestion" laQuestion=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"laQuestion"
		public Keyword getLaQuestionKeyword_4_0() { return cLaQuestionKeyword_4_0; }

		//laQuestion=EString
		public Assignment getLaQuestionAssignment_4_1() { return cLaQuestionAssignment_4_1; }

		//EString
		public RuleCall getLaQuestionEStringParserRuleCall_4_1_0() { return cLaQuestionEStringParserRuleCall_4_1_0; }

		//("widgets" "{" widgets+=Widget ("," widgets+=Widget)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"widgets"
		public Keyword getWidgetsKeyword_5_0() { return cWidgetsKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//widgets+=Widget
		public Assignment getWidgetsAssignment_5_2() { return cWidgetsAssignment_5_2; }

		//Widget
		public RuleCall getWidgetsWidgetParserRuleCall_5_2_0() { return cWidgetsWidgetParserRuleCall_5_2_0; }

		//("," widgets+=Widget)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//widgets+=Widget
		public Assignment getWidgetsAssignment_5_3_1() { return cWidgetsAssignment_5_3_1; }

		//Widget
		public RuleCall getWidgetsWidgetParserRuleCall_5_3_1_0() { return cWidgetsWidgetParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class CheckBoxElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CheckBox");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCheckBoxAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCheckBoxKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//CheckBox:
		//	{CheckBox} "CheckBox" "{" ("value" value=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{CheckBox} "CheckBox" "{" ("value" value=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{CheckBox}
		public Action getCheckBoxAction_0() { return cCheckBoxAction_0; }

		//"CheckBox"
		public Keyword getCheckBoxKeyword_1() { return cCheckBoxKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("value" value=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"value"
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }

		//value=EString
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }

		//EString
		public RuleCall getValueEStringParserRuleCall_3_1_0() { return cValueEStringParserRuleCall_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class RadioButtonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RadioButton");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRadioButtonAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRadioButtonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//RadioButton:
		//	{RadioButton} "RadioButton" "{" ("value" value=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{RadioButton} "RadioButton" "{" ("value" value=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{RadioButton}
		public Action getRadioButtonAction_0() { return cRadioButtonAction_0; }

		//"RadioButton"
		public Keyword getRadioButtonKeyword_1() { return cRadioButtonKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("value" value=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"value"
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }

		//value=EString
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }

		//EString
		public RuleCall getValueEStringParserRuleCall_3_1_0() { return cValueEStringParserRuleCall_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class TextFieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TextField");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTextFieldAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTextFieldKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//TextField:
		//	{TextField} "TextField" "{" ("value" value=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{TextField} "TextField" "{" ("value" value=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{TextField}
		public Action getTextFieldAction_0() { return cTextFieldAction_0; }

		//"TextField"
		public Keyword getTextFieldKeyword_1() { return cTextFieldKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("value" value=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"value"
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }

		//value=EString
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }

		//EString
		public RuleCall getValueEStringParserRuleCall_3_1_0() { return cValueEStringParserRuleCall_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class ComboBoxElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ComboBox");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cComboBoxAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cComboBoxKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ComboBox:
		//	{ComboBox} "ComboBox" "{" ("value" value=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{ComboBox} "ComboBox" "{" ("value" value=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{ComboBox}
		public Action getComboBoxAction_0() { return cComboBoxAction_0; }

		//"ComboBox"
		public Keyword getComboBoxKeyword_1() { return cComboBoxKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("value" value=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"value"
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }

		//value=EString
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }

		//EString
		public RuleCall getValueEStringParserRuleCall_3_1_0() { return cValueEStringParserRuleCall_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	
	private PollSystemElements pPollSystem;
	private WidgetElements pWidget;
	private UiModelElements pUiModel;
	private EStringElements pEString;
	private CheckBoxElements pCheckBox;
	private RadioButtonElements pRadioButton;
	private TextFieldElements pTextField;
	private ComboBoxElements pComboBox;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public PivotMMDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.istic.idm.PivotMMDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//PollSystem:
	//	{PollSystem} "PollSystem" "{" ("title" title=EString)? ("models" "{" models+=UiModel ("," models+=UiModel)* "}")? "}";
	public PollSystemElements getPollSystemAccess() {
		return (pPollSystem != null) ? pPollSystem : (pPollSystem = new PollSystemElements());
	}
	
	public ParserRule getPollSystemRule() {
		return getPollSystemAccess().getRule();
	}

	//Widget:
	//	CheckBox | RadioButton | TextField | ComboBox;
	public WidgetElements getWidgetAccess() {
		return (pWidget != null) ? pWidget : (pWidget = new WidgetElements());
	}
	
	public ParserRule getWidgetRule() {
		return getWidgetAccess().getRule();
	}

	//UiModel:
	//	{UiModel} "UiModel" "{" ("id" id=EString)? ("laQuestion" laQuestion=EString)? ("widgets" "{" widgets+=Widget (","
	//	widgets+=Widget)* "}")? "}";
	public UiModelElements getUiModelAccess() {
		return (pUiModel != null) ? pUiModel : (pUiModel = new UiModelElements());
	}
	
	public ParserRule getUiModelRule() {
		return getUiModelAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//CheckBox:
	//	{CheckBox} "CheckBox" "{" ("value" value=EString)? "}";
	public CheckBoxElements getCheckBoxAccess() {
		return (pCheckBox != null) ? pCheckBox : (pCheckBox = new CheckBoxElements());
	}
	
	public ParserRule getCheckBoxRule() {
		return getCheckBoxAccess().getRule();
	}

	//RadioButton:
	//	{RadioButton} "RadioButton" "{" ("value" value=EString)? "}";
	public RadioButtonElements getRadioButtonAccess() {
		return (pRadioButton != null) ? pRadioButton : (pRadioButton = new RadioButtonElements());
	}
	
	public ParserRule getRadioButtonRule() {
		return getRadioButtonAccess().getRule();
	}

	//TextField:
	//	{TextField} "TextField" "{" ("value" value=EString)? "}";
	public TextFieldElements getTextFieldAccess() {
		return (pTextField != null) ? pTextField : (pTextField = new TextFieldElements());
	}
	
	public ParserRule getTextFieldRule() {
		return getTextFieldAccess().getRule();
	}

	//ComboBox:
	//	{ComboBox} "ComboBox" "{" ("value" value=EString)? "}";
	public ComboBoxElements getComboBoxAccess() {
		return (pComboBox != null) ? pComboBox : (pComboBox = new ComboBoxElements());
	}
	
	public ParserRule getComboBoxRule() {
		return getComboBoxAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
