/*
* generated by Xtext
*/
package fr.istic.idm;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PivotMMDslStandaloneSetup extends PivotMMDslStandaloneSetupGenerated{

	public static void doSetup() {
		new PivotMMDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

