/*
 * generated by Xtext
 */
package fr.istic.idm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CssDslRuntimeModule extends fr.istic.idm.AbstractCssDslRuntimeModule {

}
