/*
* generated by Xtext
*/
package fr.istic.idm;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CssDslStandaloneSetup extends CssDslStandaloneSetupGenerated{

	public static void doSetup() {
		new CssDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

