/*
 * generated by Xtext
 */
package fr.istic.idm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CssDslUiModule extends fr.istic.idm.ui.AbstractCssDslUiModule {
	public CssDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
