/*
 * generated by Xtext
 */
package fr.istic.idm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PivotMMDslUiModule extends fr.istic.idm.ui.AbstractPivotMMDslUiModule {
	public PivotMMDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
