/*
* generated by Xtext
*/
package fr.istic.idm;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class QuestionnaireDslStandaloneSetup extends QuestionnaireDslStandaloneSetupGenerated{

	public static void doSetup() {
		new QuestionnaireDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

