/*
 * generated by Xtext
 */
package fr.istic.idm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QuestionnaireDslRuntimeModule extends fr.istic.idm.AbstractQuestionnaireDslRuntimeModule {

}
