/*
* generated by Xtext
*/
package fr.istic.idm.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.istic.idm.services.QuestionnaireDslGrammarAccess;

public class QuestionnaireDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private QuestionnaireDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.istic.idm.parser.antlr.internal.InternalQuestionnaireDslParser createParser(XtextTokenStream stream) {
		return new fr.istic.idm.parser.antlr.internal.InternalQuestionnaireDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Sondage";
	}
	
	public QuestionnaireDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QuestionnaireDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
