/**
 * generated by Xtext
 */
package fr.istic.idm.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class QuestionnaireDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
