/*
 * generated by Xtext
 */
package fr.istic.idm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QuestionnaireDslUiModule extends fr.istic.idm.ui.AbstractQuestionnaireDslUiModule {
	public QuestionnaireDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
