/**
 * generated by Xtext
 */
package fr.istic.idm.ui.contentassist;

import fr.istic.idm.ui.contentassist.AbstractCssDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class CssDslProposalProvider extends AbstractCssDslProposalProvider {
}
