/*
* generated by Xtext
*/
package fr.istic.idm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class QuestionnaireDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/istic/idm/parser/antlr/internal/InternalQuestionnaireDsl.tokens");
	}
}
