/*
* generated by Xtext
*/
package fr.istic.idm;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CssDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.istic.idm.ui.internal.CssDslActivator.getInstance().getInjector("fr.istic.idm.CssDsl");
	}
	
}
